---
root: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 9
  sourceType: module
env:
  browser: true
  es6: true
  jasmine: true
  jest: true
  node: true
globals:
  "$": true
  DEFINED_GIT_REVISION: true
  jQuery: true
  angular: true
  dorsata: true
  moment: true
  FastClick: true
  chrome: true
  Modernizr: true
  Messenger: true
  autosize: true
rules:
  accessor-pairs: off
  array-bracket-newline: off
  array-bracket-spacing: off
  array-callback-return: off
  array-element-newline: off
  arrow-body-style: off
  arrow-parens: off
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: off
  block-spacing: off
  brace-style: off
  callback-return: off
  camelcase: off
  capitalized-comments: off
  class-methods-use-this: off
  comma-dangle: warn
  comma-spacing: warn
  comma-style: off
  complexity: off
  computed-property-spacing: off
  consistent-return: off
  consistent-this: off
  constructor-super: warn
  curly: off
  default-case: off
  dot-location: off
  dot-notation: off
  eol-last: off
  eqeqeq: off
  for-direction: off
  func-call-spacing: off
  func-name-matching: off
  func-names: off
  func-style: off
  function-paren-newline: off
  generator-star-spacing:
    - error
    - after: true
      before: false
  getter-return: off
  global-require: off
  guard-for-in: off
  handle-callback-err: off
  id-blacklist: off
  id-length: off
  id-match: off
  implicit-arrow-linebreak: off
  indent:
    - warn
    - tab
    - SwitchCase: 1
  indent-legacy: off
  init-declarations: off
  jsx-quotes: off
  key-spacing:
    - warn
    - mode: minimum
  keyword-spacing: off
  line-comment-position: off
  linebreak-style: off
  lines-around-comment: off
  lines-around-directive: off
  lines-between-class-members: off
  max-depth: off
  max-len: off
  max-lines: off
  max-nested-callbacks: off
  max-params: off
  max-statements: off
  max-statements-per-line: off
  multiline-comment-style: off
  multiline-ternary: off
  new-cap: off
  new-parens: off
  newline-after-var: off
  newline-before-return: off
  newline-per-chained-call: off
  no-alert: error
  no-array-constructor: off
  no-await-in-loop: off
  no-bitwise: off
  no-buffer-constructor: off
  no-caller: off
  no-case-declarations: warn
  no-catch-shadow: off
  no-class-assign: error
  no-compare-neg-zero: warn
  no-cond-assign: warn
  no-confusing-arrow:
    - error
    - allowParens: true
  no-console: off
  no-const-assign: error
  no-constant-condition: warn
  no-continue: off
  no-control-regex: warn
  no-debugger: error
  no-delete-var: warn
  no-div-regex: off
  no-dupe-args: warn
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: warn
  no-duplicate-imports: off
  no-else-return: off
  no-empty: warn
  no-empty-character-class: error
  no-empty-function: off
  no-empty-pattern: warn
  no-eq-null: off
  no-eval: error
  no-ex-assign: warn
  no-extend-native: off
  no-extra-bind: off
  no-extra-boolean-cast: warn
  no-extra-label: off
  no-extra-parens: off
  no-extra-semi: error
  no-fallthrough: warn
  no-floating-decimal: off
  no-func-assign: warn
  no-global-assign: warn
  no-implicit-coercion: off
  no-implicit-globals: off
  no-implied-eval: off
  no-inline-comments: off
  no-inner-declarations: warn
  no-invalid-regexp: warn
  no-invalid-this: off
  no-irregular-whitespace: warn
  no-iterator: off
  no-label-var: off
  no-labels: off
  no-lone-blocks: off
  no-lonely-if: off
  no-loop-func: warn
  no-magic-numbers: off
  no-misleading-character-class: error
  no-mixed-operators: off
  no-mixed-requires: off
  no-mixed-spaces-and-tabs:
    - warn
    - smart-tabs
  no-multi-assign: off
  no-multi-spaces: off
  no-multi-str: off
  no-multiple-empty-lines: off
  no-native-reassign: off
  no-negated-condition: off
  no-negated-in-lhs: off
  no-nested-ternary: off
  no-new: off
  no-new-func: off
  no-new-object: off
  no-new-require: off
  no-new-symbol: warn
  no-new-wrappers: off
  no-obj-calls: warn
  no-octal: warn
  no-octal-escape: off
  no-param-reassign: off
  no-path-concat: off
  no-plusplus: off
  no-process-env: off
  no-process-exit: off
  no-proto: off
  no-prototype-builtins: off
  no-redeclare: warn
  no-regex-spaces: warn
  no-restricted-globals: off
  no-restricted-imports: off
  no-restricted-modules: off
  no-restricted-properties: off
  no-restricted-syntax: off
  no-return-assign: off
  no-return-await: off
  no-script-url: off
  no-self-assign: warn
  no-self-compare: off
  no-sequences: off
  no-shadow: off
  no-shadow-restricted-names: off
  no-spaced-func: warn
  no-sparse-arrays: warn
  no-sync: off
  no-tabs: off
  no-template-curly-in-string: off
  no-ternary: off
  no-this-before-super: error
  no-throw-literal: off
  no-trailing-spaces: off
  no-undef: error
  no-undef-init: off
  no-undefined: off
  no-underscore-dangle: off
  no-unexpected-multiline: warn
  no-unmodified-loop-condition: off
  no-unneeded-ternary: off
  no-unreachable: warn
  no-unsafe-finally: warn
  no-unsafe-negation: warn
  no-unused-expressions: warn # Catch misplaced 'ngInject' directives
  no-unused-labels: error
  no-unused-vars:
    - warn
    - args: none
  no-use-before-define: off
  no-useless-call: off
  no-useless-computed-key: off
  no-useless-concat: error
  no-useless-constructor: off
  no-useless-escape: off
  no-useless-rename: off
  no-useless-return: off
  no-var: warn
  no-void: off
  no-warning-comments:
    - error
    - terms:
      - nginject
  no-whitespace-before-property: off
  no-with: off
  nonblock-statement-body-position: off
  object-curly-newline: off
  object-curly-spacing: off
  object-property-newline: off
  object-shorthand: off
  one-var: off
  one-var-declaration-per-line: off
  operator-assignment:  off
  operator-linebreak: off
  padded-blocks: off
  padding-line-between-statements: off
  prefer-arrow-callback: off
  prefer-const: warn
  prefer-destructuring: off
  prefer-numeric-literals: off
  prefer-promise-reject-warns: off
  prefer-reflect: off
  prefer-rest-params: off
  prefer-spread: off
  prefer-template: off
  quote-props: off
  quotes: off
  radix: off
  require-await: off
  require-jsdoc: off
  require-yield: error
  rest-spread-spacing:
    - error
    - never
  #semi:
    #- warn
    #- never
  semi-spacing:
    - warn
    - after: true
      before: false
  semi-style: off
  sort-imports: off
  sort-keys: off
  sort-vars: off
  space-before-blocks: off
  space-before-function-paren: off
  space-in-parens: warn
  space-infix-ops: warn
  space-unary-ops: warn
  spaced-comment: off
  strict: off
  switch-colon-spacing: off
  symbol-description: off
  template-curly-spacing: error
  template-tag-spacing: off
  unicode-bom: off
  use-isnan: warn
  valid-jsdoc:
    - warn
    -
      prefer:
        arg: param
        argument: param
        class: class
        return: return
        virtual: abstract
      #matchDescription: '.+' # match any text
      preferType:
        array: array
        object: object
      requireParamDescription: false
      requireReturn: false
      requireReturnDescription: false
      requireReturnType: true
  valid-typeof: error
  vars-on-top: off
  wrap-iife: off
  wrap-regex: off
  yield-star-spacing: error
  yoda: off
